name: Build and Push Docker Image to ECR

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication with AWS
      contents: read   # Allow reading repository contents

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials using OIDC to assume the ECR_Update role
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264270514:role/ECR_Update
          aws-region: eu-central-1  # Set to the correct region: eu-central-1 (Frankfurt)

      # Step 3: Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | \
          docker login --username AWS --password-stdin 058264270514.dkr.ecr.eu-central-1.amazonaws.com

      # Step 5: Build the Docker image and tag it with 'latest'
      - name: Build Docker image
        run: |
          docker build -t 058264270514.dkr.ecr.eu-central-1.amazonaws.com/atanor_application:latest stable/

      # Step 6: Push the Docker image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker push 058264270514.dkr.ecr.eu-central-1.amazonaws.com/atanor_application:latest

      # Step 7: Log out of Docker (optional for cleanup)
      - name: Log out of Docker
        run: docker logout
